=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/schema/input_schema.json
{
    "$schema": "http://json-schema.org/draft-04/hyper-schema#",
    "description": "JSON schema for paragraph / pam inputs",
    "type": "object",
    "required": ["model_name", "nodes", "sequencenames", "target_regions"],
    "dependencies": {
        "paths": ["edges"]
    },
    "additionalProperties": false,
    "properties": {
        "model_name": {"type": "string"},
        "edges": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/edge",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "nodes": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/node",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "paths": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/path",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "sequencenames": {
            "type": "array",
            "items": {
                "type": "string",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "target_regions": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^.+:[0-9]+-[0-9]+$",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        }
    }
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/pg-complex/pg-complex-2.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr1:239404557-239404706",
            "to": "ref-chr1:239404557-239404706"
        },
        {
            "from": "ref-chr1:239404557-239404706",
            "name": "ref-chr1:239404557-239404706_ref-chr1:239404707-239404707",
            "sequences": [
                "REF",
                "chr1:239404707-1:0"
            ],
            "to": "ref-chr1:239404707-239404707"
        },
        {
            "from": "ref-chr1:239404557-239404706",
            "name": "ref-chr1:239404557-239404706_chr1:239404707-239404707:G",
            "sequences": [
                "chr1:239404707-1:1"
            ],
            "to": "chr1:239404707-239404707:G"
        },
        {
            "from": "ref-chr1:239404707-239404707",
            "name": "ref-chr1:239404707-239404707_ref-chr1:239404708-239404719",
            "sequences": [
                "REF",
                "chr1:239404707-1:0"
            ],
            "to": "ref-chr1:239404708-239404719"
        },
        {
            "from": "chr1:239404707-239404707:G",
            "name": "chr1:239404707-239404707:G_ref-chr1:239404708-239404719",
            "sequences": [
                "chr1:239404707-1:1"
            ],
            "to": "ref-chr1:239404708-239404719"
        },
        {
            "from": "ref-chr1:239404708-239404719",
            "name": "ref-chr1:239404708-239404719_chr1:239404720-239404719:ATAT",
            "sequences": [
                "chr1:239404719-1:1"
            ],
            "to": "chr1:239404720-239404719:ATAT"
        },
        {
            "from": "ref-chr1:239404708-239404719",
            "name": "ref-chr1:239404708-239404719_ref-chr1:239404720-239404728",
            "sequences": [
                "REF",
                "chr1:239404719-1:0"
            ],
            "to": "ref-chr1:239404720-239404728"
        },
        {
            "from": "chr1:239404720-239404719:ATAT",
            "name": "chr1:239404720-239404719:ATAT_ref-chr1:239404720-239404728",
            "sequences": [
                "chr1:239404719-1:1"
            ],
            "to": "ref-chr1:239404720-239404728"
        },
        {
            "from": "ref-chr1:239404720-239404728",
            "name": "ref-chr1:239404720-239404728_ref-chr1:239404729-239404731",
            "sequences": [
                "REF",
                "chr1:239404728-1:0"
            ],
            "to": "ref-chr1:239404729-239404731"
        },
        {
            "from": "ref-chr1:239404720-239404728",
            "name": "ref-chr1:239404720-239404728_ref-chr1:239404732-239404881",
            "sequences": [
                "chr1:239404728-1:1"
            ],
            "to": "ref-chr1:239404732-239404881"
        },
        {
            "from": "ref-chr1:239404729-239404731",
            "name": "ref-chr1:239404729-239404731_ref-chr1:239404732-239404881",
            "sequences": [
                "REF",
                "chr1:239404728-1:0"
            ],
            "to": "ref-chr1:239404732-239404881"
        },
        {
            "from": "ref-chr1:239404732-239404881",
            "name": "ref-chr1:239404732-239404881_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from pg-complex/pg-complex-2.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr1:239404557-239404706",
            "reference": "chr1:239404557-239404706",
            "reference_sequence": "TCTGGTAAGATGAGTCGTATTCAACTTGAGATGTTTCTCAGGCTTTGCAAAGGGTGGAGTGCTCTTTCCCACTGAAATATAAACACAATAGAGCAAGAACTCAGATGTCCGCTGGAAAATTAAGTTGAAACCGCTTCCATTAAATGTATC"
        },
        {
            "name": "ref-chr1:239404707-239404707",
            "reference": "chr1:239404707-239404707",
            "reference_sequence": "A"
        },
        {
            "name": "chr1:239404707-239404707:G",
            "position": "chr1:239404707-239404707",
            "sequence": "G"
        },
        {
            "name": "ref-chr1:239404708-239404719",
            "reference": "chr1:239404708-239404719",
            "reference_sequence": "TGCTATATCTAA"
        },
        {
            "name": "chr1:239404720-239404719:ATAT",
            "position": "chr1:239404720-239404719",
            "sequence": "ATAT"
        },
        {
            "name": "ref-chr1:239404720-239404728",
            "reference": "chr1:239404720-239404728",
            "reference_sequence": "ATATATATA"
        },
        {
            "name": "ref-chr1:239404729-239404731",
            "reference": "chr1:239404729-239404731",
            "reference_sequence": "TAT"
        },
        {
            "name": "ref-chr1:239404732-239404881",
            "reference": "chr1:239404732-239404881",
            "reference_sequence": "ATATATATATATATATATATATATATGGAAAATATGGTTAACAATGTTCACAGGGTACTATAAAAACAGAAAGTGTTATCTCAAATATACGCAGTTCTTAACTTTTTTTGTTTTTCTCTTGAGTTCTATCAGGGAGCTGACTATCAAAAA"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr1:239404557-239404706",
                "ref-chr1:239404707-239404707",
                "ref-chr1:239404708-239404719",
                "ref-chr1:239404720-239404728",
                "ref-chr1:239404729-239404731",
                "ref-chr1:239404732-239404881"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "REF",
        "chr1:239404707-1:0",
        "chr1:239404707-1:1",
        "chr1:239404719-1:0",
        "chr1:239404719-1:1",
        "chr1:239404728-1:0",
        "chr1:239404728-1:1"
    ],
    "target_regions": [
        "chr1:239404557-239404881"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/insertions/insertion-test-1.noas.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr20:149008-149013",
            "to": "ref-chr20:149008-149013"
        },
        {
            "from": "ref-chr20:149008-149013",
            "name": "ref-chr20:149008-149013_chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC",
            "sequences": [
                "HG002_pbsv.INS.49079:1"
            ],
            "to": "chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC"
        },
        {
            "from": "ref-chr20:149008-149013",
            "name": "ref-chr20:149008-149013_ref-chr20:149014-149018",
            "sequences": [
                "HG002_pbsv.INS.49079:0",
                "REF"
            ],
            "to": "ref-chr20:149014-149018"
        },
        {
            "from": "chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC",
            "name": "chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC_ref-chr20:149014-149018",
            "sequences": [
                "HG002_pbsv.INS.49079:1"
            ],
            "to": "ref-chr20:149014-149018"
        },
        {
            "from": "ref-chr20:149014-149018",
            "name": "ref-chr20:149014-149018_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from ../paragraph-tools/share/test-data/paragraph/insertions/insertion-test-1.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr20:149008-149013",
            "reference": "chr20:149008-149013",
            "reference_sequence": "GAACAA"
        },
        {
            "name": "chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC",
            "position": "chr20:149014-149013",
            "sequence": "CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC"
        },
        {
            "name": "ref-chr20:149014-149018",
            "reference": "chr20:149014-149018",
            "reference_sequence": "CCATA"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr20:149008-149013",
                "ref-chr20:149014-149018"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        },
        {
            "nodes": [
                "ref-chr20:149008-149013",
                "chr20:149014-149013:CCATATTTGGGAGGCAATTTTACCTGTTCTCAAGGCCGCATCTCTACCCCATCTCATGCGAATCCTGAC",
                "ref-chr20:149014-149018"
            ],
            "path_id": "ALT|1",
            "sequence": "ALT"
        }
    ],
    "sequencenames": [
        "ALT",
        "HG002_pbsv.INS.49079:0",
        "HG002_pbsv.INS.49079:1",
        "REF"
    ],
    "target_regions": [
        "chr20:149008-149018"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/simple/swap-example-2-split.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr5:70243962-70244111",
            "to": "ref-chr5:70243962-70244111"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_ref-chr5:70244112-70244113",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244112-70244113"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_chr5:70244112-70244113:AT",
            "sequences": [
                "ALT"
            ],
            "to": "chr5:70244112-70244113:AT"
        },
        {
            "from": "ref-chr5:70244112-70244113",
            "name": "ref-chr5:70244112-70244113_ref-chr5:70244114-70244115",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244114-70244115"
        },
        {
            "from": "chr5:70244112-70244113:AT",
            "name": "chr5:70244112-70244113:AT_ref-chr5:70244114-70244115",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr5:70244114-70244115"
        },
        {
            "from": "ref-chr5:70244114-70244115",
            "name": "ref-chr5:70244114-70244115_ref-chr5:70244116-70244116",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244116-70244116"
        },
        {
            "from": "ref-chr5:70244114-70244115",
            "name": "ref-chr5:70244114-70244115_chr5:70244116-70244116:G",
            "sequences": [
                "ALT"
            ],
            "to": "chr5:70244116-70244116:G"
        },
        {
            "from": "ref-chr5:70244116-70244116",
            "name": "ref-chr5:70244116-70244116_ref-chr5:70244117-70244266",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244117-70244266"
        },
        {
            "from": "chr5:70244116-70244116:G",
            "name": "chr5:70244116-70244116:G_ref-chr5:70244117-70244266",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr5:70244117-70244266"
        },
        {
            "from": "ref-chr5:70244117-70244266",
            "name": "ref-chr5:70244117-70244266_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from simple/swap-example-2-split.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr5:70243962-70244111",
            "reference": "chr5:70243962-70244111"
        },
        {
            "name": "ref-chr5:70244112-70244113",
            "reference": "chr5:70244112-70244113"
        },
        {
            "name": "chr5:70244112-70244113:AT",
            "position": "chr5:70244112-70244113",
            "sequence": "AT"
        },
        {
            "name": "ref-chr5:70244114-70244115",
            "reference": "chr5:70244114-70244115"
        },
        {
            "name": "ref-chr5:70244116-70244116",
            "reference": "chr5:70244116-70244116"
        },
        {
            "name": "chr5:70244116-70244116:G",
            "position": "chr5:70244116-70244116",
            "sequence": "G"
        },
        {
            "name": "ref-chr5:70244117-70244266",
            "reference": "chr5:70244117-70244266"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr5:70243962-70244111",
                "ref-chr5:70244112-70244113",
                "ref-chr5:70244114-70244115",
                "ref-chr5:70244116-70244116",
                "ref-chr5:70244117-70244266"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr5:70243962-70244266"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/basic/del-with-ref-node-array.json
{
  "model_name": "Deletion graph with a node specifying multiple reference locations with identical sequence",
  "nodes": [
    {
      "name": "ref-MultipleRefLocations:1-40",
      "reference": "MultipleRefLocations:1-40",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-MultipleRefLocations:41-60",
      "reference": [
        "MultipleRefLocations:41-60",
        "MultipleRefLocations:81-100",
        "MultipleRefLocations:101-120"
      ],
      "sequences": [
        "DUP"
      ]
    },
    {
      "name": "ref-MultipleRefLocations:61-80",
      "reference": "MultipleRefLocations:61-80",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-MultipleRefLocations:121-140",
      "reference": "MultipleRefLocations:121-140",
      "sequences": [
        "REF"
      ]
    }
  ],
  "sequencenames": [
    "REF",
    "DUP"
  ],
  "target_regions": [
    "SimpleDeletion:1-100"
  ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/basic/del-with-edges-nodes.json
{
  "model_name": "Sample graph with edges and nodes specified for a deletion",
  "edges": [
    {
      "from": "source",
      "to": "ref-SimpleDeletion:1-40"
    },
    {
      "from": "ref-SimpleDeletion:61-100",
      "to": "sink"
    },
    {
      "from": "ref-SimpleDeletion:1-40",
      "to": "ref-SimpleDeletion:41-60",
      "sequences": [
        "REF"
      ]
    },
    {
      "from": "ref-SimpleDeletion:1-40",
      "to": "ref-SimpleDeletion:61-100",
      "sequences": [
        "ALT"
      ]
    },
    {
      "from": "ref-SimpleDeletion:41-60",
      "to": "ref-SimpleDeletion:61-100"
    }
  ],
  "nodes": [
    {
      "name": "source",
      "sequence": "NNNNN"
    },
    {
      "name": "ref-SimpleDeletion:1-40",
      "reference": "SimpleDeletion:1-40",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:41-60",
      "reference": "SimpleDeletion:41-60",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:61-100",
      "reference": "SimpleDeletion:61-100",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "sink",
      "sequence": "NNNNN"
    }
  ],
  "paths": [
    {
      "nodes": [
        "source",
        "ref-SimpleDeletion:1-40",
        "ref-SimpleDeletion:41-60",
        "ref-SimpleDeletion:61-100",
        "sink"
      ],
      "nucleotide_length": 100,
      "path_id": "REF|1",
      "sequence": "REF"
    },
    {
      "nodes": [
        "source",
        "ref-SimpleDeletion:1-40",
        "ref-SimpleDeletion:61-100",
        "sink"
      ],
      "nucleotide_length": 80,
      "path_id": "ALT|1",
      "sequence": "ALT"
    }
  ],
  "sequencenames": [
    "REF",
    "ALT"
  ],
  "target_regions": [
    "SimpleDeletion:1-100"
  ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/genotyping_test_2/chrB.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chrB:1350-1500",
            "to": "ref-chrB:1350-1500"
        },
        {
            "from": "ref-chrB:1350-1500",
            "name": "ref-chrB:1350-1500_chrB:1501-1509:TCAGGTTGTCTTATGCTTGGCATCGTTCTT",
            "sequences": [
                "swap2:1"
            ],
            "to": "chrB:1501-1509:TCAGGTTGTCTTATGCTTGGCATCGTTCTT"
        },
        {
            "from": "ref-chrB:1350-1500",
            "name": "ref-chrB:1350-1500_ref-chrB:1501-1509",
            "sequences": [
                "REF",
                "swap2:0"
            ],
            "to": "ref-chrB:1501-1509"
        },
        {
            "from": "chrB:1501-1509:TCAGGTTGTCTTATGCTTGGCATCGTTCTT",
            "name": "chrB:1501-1509:TCAGGTTGTCTTATGCTTGGCATCGTTCTT_ref-chrB:1510-1659",
            "sequences": [
                "swap2:1"
            ],
            "to": "ref-chrB:1510-1659"
        },
        {
            "from": "ref-chrB:1501-1509",
            "name": "ref-chrB:1501-1509_ref-chrB:1510-1659",
            "sequences": [
                "REF",
                "swap2:0"
            ],
            "to": "ref-chrB:1510-1659"
        },
        {
            "from": "ref-chrB:1510-1659",
            "name": "ref-chrB:1510-1659_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from /Users/schen6/Documents/paragraph-tools/share/test-data/genotyping_test_2/chrB.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chrB:1350-1500",
            "reference": "chrB:1350-1500",
            "reference_sequence": "TCTAACAATTACGGAGGAGAACCGGTCTCCCCCCACGGTGGAGCGTATACGTCGTTAATGGTGGGGAAGTCAATACGACCGACTGTCCATGGTCATGCCCCTATCGTCGGATTCACGCTGCTTTACCTCAAAGTCAACCCAGCCGTAGTTA"
        },
        {
            "name": "chrB:1501-1509:TCAGGTTGTCTTATGCTTGGCATCGTTCTT",
            "position": "chrB:1501-1509",
            "sequence": "TCAGGTTGTCTTATGCTTGGCATCGTTCTT"
        },
        {
            "name": "ref-chrB:1501-1509",
            "reference": "chrB:1501-1509",
            "reference_sequence": "GGCCATACG"
        },
        {
            "name": "ref-chrB:1510-1659",
            "reference": "chrB:1510-1659",
            "reference_sequence": "CACAGGCTATCTGTAAATCATCAAATCATGGTACCTATCTCGGGTACCACATTAATCTTACGCGCCAGAGCCTTGGAATGGGCTCTTCAGTTACCTGTAAGCGGCTTCTATCTTCAGCGCAGAGCGTGCACCGGGTTATAGGCCTAGAGG"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chrB:1350-1500",
                "ref-chrB:1501-1509",
                "ref-chrB:1510-1659"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "REF",
        "swap2:0",
        "swap2:1"
    ],
    "target_regions": [
        "chrB:1350-1659"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/simple/swap-example-1.json
{
  "model_name": "paragraph example based on a swap / insertion",
  "sequencenames": [
    "REF",
    "ALT"
  ],
  "nodes": [
    {
      "name": "LF",
      "reference": "chr6:62832517-62832616"
    },
    {
      "name": "DEL",
      "reference": "chr6:62832617-62832842"
    },
    {
      "name": "INS",
      "sequence": "ACGTGTCTTATATTATAAAACTGCACGTTATACCT"
    },
    {
      "name": "RF",
      "reference": "chr6:62832843-62832943"
    }
  ],
  "edges": [
    {
      "from": "LF",
      "to": "RF"
    },
    {
      "from": "LF",
      "to": "DEL",
      "sequences": [
        "REF"
      ]
    },
    {
      "from": "LF",
      "to": "INS",
      "sequences": [
        "ALT"
      ]
    },
    {
      "from": "DEL",
      "to": "RF",
      "sequences": [
        "REF"
      ]
    },
    {
      "from": "INS",
      "to": "RF",
      "sequences": [
        "ALT"
      ]
    }
  ],
  "target_regions": [
    "chr6:62832500-62833000"
  ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/haplo-complex/overlapping.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr5:850-999",
            "to": "ref-chr5:850-999"
        },
        {
            "from": "ref-chr5:850-999",
            "name": "ref-chr5:850-999_ref-chr5:1000-1000",
            "sequences": [
                "REF",
                "Seq1"
            ],
            "to": "ref-chr5:1000-1000"
        },
        {
            "from": "ref-chr5:850-999",
            "name": "ref-chr5:850-999_chr5:1000-1000:T",
            "sequences": [
                "Seq2"
            ],
            "to": "chr5:1000-1000:T"
        },
        {
            "from": "ref-chr5:1000-1000",
            "name": "ref-chr5:1000-1000_chr5:1006-1006:T",
            "sequences": [
                "Seq1"
            ],
            "to": "chr5:1006-1006:T"
        },
        {
            "from": "ref-chr5:1000-1000",
            "name": "ref-chr5:1000-1000_ref-chr5:1001-1002",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:1001-1002"
        },
        {
            "from": "chr5:1006-1006:T",
            "name": "chr5:1006-1006:T_ref-chr5:1007-1999",
            "sequences": [
                "Seq1"
            ],
            "to": "ref-chr5:1007-1999"
        },
        {
            "from": "chr5:1000-1000:T",
            "name": "chr5:1000-1000:T_ref-chr5:1001-1002",
            "sequences": [
                "Seq2"
            ],
            "to": "ref-chr5:1001-1002"
        },
        {
            "from": "ref-chr5:1001-1002",
            "name": "ref-chr5:1001-1002_ref-chr5:1003-1003",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:1003-1003"
        },
        {
            "from": "ref-chr5:1001-1002",
            "name": "ref-chr5:1001-1002_ref-chr5:1004-1006",
            "sequences": [
                "Seq2"
            ],
            "to": "ref-chr5:1004-1006"
        },
        {
            "from": "ref-chr5:1003-1003",
            "name": "ref-chr5:1003-1003_ref-chr5:1004-1006",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:1004-1006"
        },
        {
            "from": "ref-chr5:1004-1006",
            "name": "ref-chr5:1004-1006_ref-chr5:1007-1999",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:1007-1999"
        },
        {
            "from": "ref-chr5:1007-1999",
            "name": "ref-chr5:1007-1999_ref-chr5:2000-2000",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:2000-2000"
        },
        {
            "from": "ref-chr5:1007-1999",
            "name": "ref-chr5:1007-1999_chr5:2000-2000:T",
            "sequences": [
                "Seq1"
            ],
            "to": "chr5:2000-2000:T"
        },
        {
            "from": "ref-chr5:2000-2000",
            "name": "ref-chr5:2000-2000_chr5:2001-2000:TT",
            "sequences": [
                "Seq2"
            ],
            "to": "chr5:2001-2000:TT"
        },
        {
            "from": "ref-chr5:2000-2000",
            "name": "ref-chr5:2000-2000_ref-chr5:2001-2001",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:2001-2001"
        },
        {
            "from": "chr5:2001-2000:TT",
            "name": "chr5:2001-2000:TT_ref-chr5:2001-2001",
            "sequences": [
                "Seq2"
            ],
            "to": "ref-chr5:2001-2001"
        },
        {
            "from": "chr5:2000-2000:T",
            "name": "chr5:2000-2000:T_ref-chr5:2001-2001",
            "sequences": [
                "Seq1"
            ],
            "to": "ref-chr5:2001-2001"
        },
        {
            "from": "ref-chr5:2001-2001",
            "name": "ref-chr5:2001-2001_ref-chr5:2002-2002",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:2002-2002"
        },
        {
            "from": "ref-chr5:2001-2001",
            "name": "ref-chr5:2001-2001_chr5:2002-2002:T",
            "sequences": [
                "Seq2"
            ],
            "to": "chr5:2002-2002:T"
        },
        {
            "from": "ref-chr5:2001-2001",
            "name": "ref-chr5:2001-2001_ref-chr5:2003-2152",
            "sequences": [
                "Seq1"
            ],
            "to": "ref-chr5:2003-2152"
        },
        {
            "from": "ref-chr5:2002-2002",
            "name": "ref-chr5:2002-2002_ref-chr5:2003-2152",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:2003-2152"
        },
        {
            "from": "chr5:2002-2002:T",
            "name": "chr5:2002-2002:T_ref-chr5:2003-2152",
            "sequences": [
                "Seq2"
            ],
            "to": "ref-chr5:2003-2152"
        },
        {
            "from": "ref-chr5:2003-2152",
            "name": "ref-chr5:2003-2152_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from haplo-complex/overlapping.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr5:850-999",
            "reference": "chr5:850-999"
        },
        {
            "name": "ref-chr5:1000-1000",
            "reference": "chr5:1000-1000"
        },
        {
            "name": "chr5:1006-1006:T",
            "position": "chr5:1006-1006",
            "sequence": "T"
        },
        {
            "name": "chr5:1000-1000:T",
            "position": "chr5:1000-1000",
            "sequence": "T"
        },
        {
            "name": "ref-chr5:1001-1002",
            "reference": "chr5:1001-1002"
        },
        {
            "name": "ref-chr5:1003-1003",
            "reference": "chr5:1003-1003"
        },
        {
            "name": "ref-chr5:1004-1006",
            "reference": "chr5:1004-1006"
        },
        {
            "name": "ref-chr5:1007-1999",
            "reference": "chr5:1007-1999"
        },
        {
            "name": "ref-chr5:2000-2000",
            "reference": "chr5:2000-2000"
        },
        {
            "name": "chr5:2001-2000:TT",
            "position": "chr5:2001-2000",
            "sequence": "TT"
        },
        {
            "name": "chr5:2000-2000:T",
            "position": "chr5:2000-2000",
            "sequence": "T"
        },
        {
            "name": "ref-chr5:2001-2001",
            "reference": "chr5:2001-2001"
        },
        {
            "name": "ref-chr5:2002-2002",
            "reference": "chr5:2002-2002"
        },
        {
            "name": "chr5:2002-2002:T",
            "position": "chr5:2002-2002",
            "sequence": "T"
        },
        {
            "name": "ref-chr5:2003-2152",
            "reference": "chr5:2003-2152"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr5:850-999",
                "ref-chr5:1000-1000",
                "ref-chr5:1001-1002",
                "ref-chr5:1003-1003",
                "ref-chr5:1004-1006",
                "ref-chr5:1007-1999",
                "ref-chr5:2000-2000",
                "ref-chr5:2001-2001",
                "ref-chr5:2002-2002",
                "ref-chr5:2003-2152"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "REF",
        "Seq1",
        "Seq2"
    ],
    "target_regions": [
        "chr5:850-2152"
    ]
}
