=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/schema/input_schema.json
{
    "$schema": "http://json-schema.org/draft-04/hyper-schema#",
    "description": "JSON schema for paragraph / pam inputs",
    "type": "object",
    "required": ["model_name", "nodes", "sequencenames", "target_regions"],
    "dependencies": {
        "paths": ["edges"]
    },
    "additionalProperties": false,
    "properties": {
        "model_name": {"type": "string"},
        "edges": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/edge",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "nodes": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/node",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "paths": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/path",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "sequencenames": {
            "type": "array",
            "items": {
                "type": "string",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "target_regions": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^.+:[0-9]+-[0-9]+$",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        }
    }
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/simple/swap-example-5.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr5:70243962-70244112",
            "to": "ref-chr5:70243962-70244112"
        },
        {
            "from": "source",
            "name": "source_ref-chr5:70248850-70248999",
            "to": "ref-chr5:70248850-70248999"
        },
        {
            "from": "ref-chr5:70243962-70244112",
            "name": "ref-chr5:70243962-70244112_ref-chr5:70244113-70244412",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244113-70244412"
        },
        {
            "from": "ref-chr5:70243962-70244112",
            "name": "ref-chr5:70243962-70244112_chr5:70244113-70248999:ACACAC",
            "sequences": [
                "ALT"
            ],
            "to": "chr5:70244113-70248999:ACACAC"
        },
        {
            "from": "ref-chr5:70244113-70244412",
            "name": "ref-chr5:70244113-70244412_sink",
            "to": "sink"
        },
        {
            "from": "chr5:70244113-70248999:ACACAC",
            "name": "chr5:70244113-70248999:ACACAC_ref-chr5:70249000-70249149",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr5:70249000-70249149"
        },
        {
            "from": "ref-chr5:70248850-70248999",
            "name": "ref-chr5:70248850-70248999_ref-chr5:70249000-70249149",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70249000-70249149"
        },
        {
            "from": "ref-chr5:70249000-70249149",
            "name": "ref-chr5:70249000-70249149_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from simple/swap-example-5.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr5:70243962-70244112",
            "reference": "chr5:70243962-70244112"
        },
        {
            "name": "ref-chr5:70244113-70244412",
            "reference": "chr5:70244113-70244412"
        },
        {
            "name": "chr5:70244113-70248999:ACACAC",
            "position": "chr5:70244113-70248999",
            "sequence": "ACACAC"
        },
        {
            "name": "ref-chr5:70248850-70248999",
            "reference": "chr5:70248850-70248999"
        },
        {
            "name": "ref-chr5:70249000-70249149",
            "reference": "chr5:70249000-70249149"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr5:70243962-70244112",
                "ref-chr5:70244113-70244412"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        },
        {
            "nodes": [
                "ref-chr5:70248850-70248999",
                "ref-chr5:70249000-70249149"
            ],
            "path_id": "REF|2",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr5:70243962-70244412",
        "chr5:70248850-70249149"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/simple/del-example-3.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr5:70243962-70244111",
            "to": "ref-chr5:70243962-70244111"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_ref-chr5:70244112-70245000",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244112-70245000"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_ref-chr5:70245001-70245150",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr5:70245001-70245150"
        },
        {
            "from": "ref-chr5:70244112-70245000",
            "name": "ref-chr5:70244112-70245000_ref-chr5:70245001-70245150",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70245001-70245150"
        },
        {
            "from": "ref-chr5:70245001-70245150",
            "name": "ref-chr5:70245001-70245150_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from simple/del-example-3.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr5:70243962-70244111",
            "reference": "chr5:70243962-70244111"
        },
        {
            "name": "ref-chr5:70244112-70245000",
            "reference": "chr5:70244112-70245000"
        },
        {
            "name": "ref-chr5:70245001-70245150",
            "reference": "chr5:70245001-70245150"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr5:70243962-70244111",
                "ref-chr5:70244112-70245000",
                "ref-chr5:70245001-70245150"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr5:70243962-70245150"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/basic/del-with-duplicate-node-names.json
{
  "model_name": "Sample graph with two nodes that have the same ID (fatal)",
  "nodes": [
    {
      "name": "ref-SimpleDeletion:1-40",
      "references": "SimpleDeletion:1-40",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:1-40",
      "references": "SimpleDeletion:41-60",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:61-100",
      "references": "SimpleDeletion:61-100",
      "sequences": [
        "REF"
      ]
    }
  ],
  "sequencenames": [
    "REF"
  ],
  "target_regions": [
    "SimpleDeletion:1-100"
  ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/basic/del-with-no-ref-or-seq-node-key.json
{
  "model_name": "Sample graph with a node that has no reference or sequence key (fatal)",
  "nodes": [
    {
      "name": "ref-SimpleDeletion:1-40",
      "reference": "SimpleDeletion:1-40",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:41-60",
      "foo": "SimpleDeletion:41-60",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:61-100",
      "reference": "SimpleDeletion:61-100",
      "sequences": [
        "REF"
      ]
    }
  ],
  "sequencenames": [
    "REF"
  ],
  "target_regions": [
    "SimpleDeletion:1-100"
  ]
}
