=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/schema/input_schema.json
{
    "$schema": "http://json-schema.org/draft-04/hyper-schema#",
    "description": "JSON schema for paragraph / pam inputs",
    "type": "object",
    "required": ["model_name", "nodes", "sequencenames", "target_regions"],
    "dependencies": {
        "paths": ["edges"]
    },
    "additionalProperties": false,
    "properties": {
        "model_name": {"type": "string"},
        "edges": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/edge",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "nodes": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/node",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "paths": {
            "type": "array",
            "items": {
                "$ref": "common_definitions.json#/definitions/path",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "sequencenames": {
            "type": "array",
            "items": {
                "type": "string",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        },
        "target_regions": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^.+:[0-9]+-[0-9]+$",
                "$ref": "common_definitions.json#/definitions/min_1_unique_list"
            }
        }
    }
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/genotyping_test_2/chrC.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chrC:1350-1500",
            "to": "ref-chrC:1350-1500"
        },
        {
            "from": "ref-chrC:1350-1500",
            "name": "ref-chrC:1350-1500_chrC:1501-1697:CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG",
            "sequences": [
                "swap3:1"
            ],
            "to": "chrC:1501-1697:CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG"
        },
        {
            "from": "ref-chrC:1350-1500",
            "name": "ref-chrC:1350-1500_ref-chrC:1501-1697",
            "sequences": [
                "REF",
                "swap3:0"
            ],
            "to": "ref-chrC:1501-1697"
        },
        {
            "from": "chrC:1501-1697:CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG",
            "name": "chrC:1501-1697:CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG_ref-chrC:1698-1699",
            "sequences": [
                "swap3:1"
            ],
            "to": "ref-chrC:1698-1699"
        },
        {
            "from": "ref-chrC:1501-1697",
            "name": "ref-chrC:1501-1697_ref-chrC:1698-1699",
            "sequences": [
                "REF",
                "swap3:0"
            ],
            "to": "ref-chrC:1698-1699"
        },
        {
            "from": "ref-chrC:1698-1699",
            "name": "ref-chrC:1698-1699_ref-chrC:1700-1849",
            "sequences": [
                "REF",
                "swap3:0",
                "swap3:1"
            ],
            "to": "ref-chrC:1700-1849"
        },
        {
            "from": "ref-chrC:1700-1849",
            "name": "ref-chrC:1700-1849_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from ../genotyping_test_2/chrC.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chrC:1350-1500",
            "reference": "chrC:1350-1500",
            "reference_sequence": "CTAACATACGGAAACGGTCCGCCTGGTCCACCATCATGCCTCCCGCCCATCGGTCAAAATGAATTTCCTCCTTTTAACCGGCAGGGTTGATAAGGTGCTCATAGAGAGCGTACCCTCTTAGTAGAGAACCAGGCACCGTTACCACTTTGTC"
        },
        {
            "name": "chrC:1501-1697:CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG",
            "position": "chrC:1501-1697",
            "sequence": "CGGAGATACCCTCTGTCTCCGCTAACATTTCCCCGCGGACAAAATTTGTCGGCTGGGAGGAATAGGTGCAAACGCATAATATACCCCTCTTACTTTTTGTTAGGGTCTAGTCCGAATCTAAAAAATGACTAAGGACTCTCAGAGTGATGGATATATGCCTCGCGACGCCGATCTGTGCTTATGTCGCAGCTTTGGCATCAAACCAGTTTCACATACCCTGCCTAAAAGATTCCCATACTGCGAAATCGCAAGATTGTACAAGTTGTAGTCTGTGCGCCAGCGTGAGCACGGCACTCG"
        },
        {
            "name": "ref-chrC:1501-1697",
            "reference": "chrC:1501-1697",
            "reference_sequence": "GCGTTGTAAGCTACCATATTCAATCTGTGCCAGGGATCGAGCCACAGGCACCGCTCAATCTCGCGGGAGATTGTGCAAAGAGTCTTACCTTTCGTCGACCTCCGCCTCGCTCGTGAATCTTGCGATCGATTGAAAGTCACGGGTAGAGTGATGTTCGGGCGAATCAGACAGGCAGATGCAATGGAGGTTCCCGGATA"
        },
        {
            "name": "ref-chrC:1698-1699",
            "reference": "chrC:1698-1699",
            "reference_sequence": "GT"
        },
        {
            "name": "ref-chrC:1700-1849",
            "reference": "chrC:1700-1849",
            "reference_sequence": "GTCAGCTATCTTTCTTTGAGCGCCTGGAATCGATCTTGGCTCCGTATGTACGGAAGGACGTGGGGAGCCCAGTCCGTTCCCTCAACGGATCAGATCGCTCTCGAAATTATCGCAGATGGGCGTGAGGAATTTGGGCCCCAACGTTTACCT"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chrC:1350-1500",
                "ref-chrC:1501-1697",
                "ref-chrC:1698-1699",
                "ref-chrC:1700-1849"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "REF",
        "swap3:0",
        "swap3:1"
    ],
    "target_regions": [
        "chrC:1350-1849"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/variants/ref-vars.json
{
    "edges": [
        {
            "from": "A",
            "name": "A_ref-chr5:1000-1001",
            "to": "ref-chr5:1000-1001"
        },
        {
            "from": "A",
            "name": "A_ref-chr5:1002-1006",
            "to": "ref-chr5:1002-1006"
        },
        {
            "from": "A",
            "name": "A_chr5:1000-1005:TTTTT",
            "to": "chr5:1000-1005:TTTTT"
        },
        {
            "from": "ref-chr5:1000-1001",
            "name": "ref-chr5:1000-1001_ref-chr5:1002-1006",
            "to": "ref-chr5:1002-1006"
        },
        {
            "from": "ref-chr5:1002-1006",
            "name": "ref-chr5:1002-1006_ref-chr5:1007-1007",
            "to": "ref-chr5:1007-1007"
        },
        {
            "from": "ref-chr5:1002-1006",
            "name": "ref-chr5:1002-1006_chr5:1007-1007:C",
            "to": "chr5:1007-1007:C"
        },
        {
            "from": "ref-chr5:1007-1007",
            "name": "ref-chr5:1007-1007_ref-chr5:1008-1010",
            "to": "ref-chr5:1008-1010"
        },
        {
            "from": "chr5:1007-1007:C",
            "name": "chr5:1007-1007:C_ref-chr5:1008-1010",
            "to": "ref-chr5:1008-1010"
        },
        {
            "from": "ref-chr5:1008-1010",
            "name": "ref-chr5:1008-1010_D",
            "to": "D"
        },
        {
            "from": "ref-chr5:1008-1010",
            "name": "ref-chr5:1008-1010_C",
            "to": "C"
        },
        {
            "from": "chr5:1000-1005:TTTTT",
            "name": "chr5:1000-1005:TTTTT_chr5:1006-1005:G",
            "to": "chr5:1006-1005:G"
        },
        {
            "from": "chr5:1000-1005:TTTTT",
            "name": "chr5:1000-1005:TTTTT_D",
            "to": "D"
        },
        {
            "from": "chr5:1000-1005:TTTTT",
            "name": "chr5:1000-1005:TTTTT_C",
            "to": "C"
        },
        {
            "from": "chr5:1006-1005:G",
            "name": "chr5:1006-1005:G_D",
            "to": "D"
        },
        {
            "from": "chr5:1006-1005:G",
            "name": "chr5:1006-1005:G_C",
            "to": "C"
        }
    ],
    "model_name": "Test graph for variant insertion",
    "nodes": [
        {
            "name": "A",
            "reference": "chr5:850-999"
        },
        {
            "name": "ref-chr5:1000-1001",
            "reference": "chr5:1000-1001"
        },
        {
            "name": "ref-chr5:1002-1006",
            "reference": "chr5:1002-1006"
        },
        {
            "name": "ref-chr5:1007-1007",
            "reference": "chr5:1007-1007"
        },
        {
            "name": "chr5:1007-1007:C",
            "position": "chr5:1007-1007",
            "sequence": "C"
        },
        {
            "name": "ref-chr5:1008-1010",
            "reference": "chr5:1008-1010"
        },
        {
            "name": "chr5:1000-1005:TTTTT",
            "position": "chr5:1000-1005",
            "sequence": "TTTTT"
        },
        {
            "name": "chr5:1006-1005:G",
            "position": "chr5:1006-1005",
            "sequence": "G"
        },
        {
            "name": "D",
            "reference": "chr5:1101-1200"
        },
        {
            "name": "C",
            "reference": "chr5:1001-1100"
        }
    ],
    "paths": [],
    "sequencenames": [],
    "target_regions": []
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/long-del/chr4-21369091-21376907.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr4:21376758-21376907",
            "to": "ref-chr4:21376758-21376907"
        },
        {
            "from": "source",
            "name": "source_ref-chr4:21368941-21369090",
            "to": "ref-chr4:21368941-21369090"
        },
        {
            "from": "ref-chr4:21376758-21376907",
            "name": "ref-chr4:21376758-21376907_ref-chr4:21376908-21377057",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr4:21376908-21377057"
        },
        {
            "from": "ref-chr4:21368941-21369090",
            "name": "ref-chr4:21368941-21369090_ref-chr4:21369091-21369091",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr4:21369091-21369091"
        },
        {
            "from": "ref-chr4:21369091-21369091",
            "name": "ref-chr4:21369091-21369091_ref-chr4:21376908-21377057",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr4:21376908-21377057"
        },
        {
            "from": "ref-chr4:21369091-21369091",
            "name": "ref-chr4:21369091-21369091_ref-chr4:21369092-21369241",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr4:21369092-21369241"
        },
        {
            "from": "ref-chr4:21376908-21377057",
            "name": "ref-chr4:21376908-21377057_sink",
            "to": "sink"
        },
        {
            "from": "ref-chr4:21369092-21369241",
            "name": "ref-chr4:21369092-21369241_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from /Users/schen6/Documents/paragraph-tools/share/test-data/paragraph/long-del/chr4-21369091-21376907.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr4:21376758-21376907",
            "reference": "chr4:21376758-21376907"
        },
        {
            "name": "ref-chr4:21368941-21369090",
            "reference": "chr4:21368941-21369090"
        },
        {
            "name": "ref-chr4:21369091-21369091",
            "reference": "chr4:21369091-21369091"
        },
        {
            "name": "ref-chr4:21376908-21377057",
            "reference": "chr4:21376908-21377057"
        },
        {
            "name": "ref-chr4:21369092-21369241",
            "reference": "chr4:21369092-21369241"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr4:21376758-21376907",
                "ref-chr4:21376908-21377057"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        },
        {
            "nodes": [
                "ref-chr4:21368941-21369090",
                "ref-chr4:21369091-21369091",
                "ref-chr4:21369092-21369241"
            ],
            "path_id": "REF|2",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr4:21368941-21369241",
        "chr4:21376758-21377057"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/pg-het-ins/pg-het-ins.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr1:939420-939570",
            "to": "ref-chr1:939420-939570"
        },
        {
            "from": "ref-chr1:939420-939570",
            "name": "ref-chr1:939420-939570_chr1:939571-939570:CCCTGGAGGACC",
            "sequences": [
                "ALT"
            ],
            "to": "chr1:939571-939570:CCCTGGAGGACC"
        },
        {
            "from": "ref-chr1:939420-939570",
            "name": "ref-chr1:939420-939570_ref-chr1:939571-939720",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr1:939571-939720"
        },
        {
            "from": "chr1:939571-939570:CCCTGGAGGACC",
            "name": "chr1:939571-939570:CCCTGGAGGACC_ref-chr1:939571-939720",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr1:939571-939720"
        },
        {
            "from": "ref-chr1:939571-939720",
            "name": "ref-chr1:939571-939720_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from pg-het-ins/pg-het-ins.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr1:939420-939570",
            "reference": "chr1:939420-939570"
        },
        {
            "name": "chr1:939571-939570:CCCTGGAGGACC",
            "position": "chr1:939571-939570",
            "sequence": "CCCTGGAGGACC"
        },
        {
            "name": "ref-chr1:939571-939720",
            "reference": "chr1:939571-939720"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr1:939420-939570",
                "ref-chr1:939571-939720"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr1:939420-939720"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/genotyping_test_2/chrA.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chrA:1350-1502",
            "to": "ref-chrA:1350-1502"
        },
        {
            "from": "ref-chrA:1350-1502",
            "name": "ref-chrA:1350-1502_chrA:1503-1506:AGTAA",
            "sequences": [
                "swap1:1"
            ],
            "to": "chrA:1503-1506:AGTAA"
        },
        {
            "from": "ref-chrA:1350-1502",
            "name": "ref-chrA:1350-1502_ref-chrA:1503-1506",
            "sequences": [
                "REF",
                "swap1:0"
            ],
            "to": "ref-chrA:1503-1506"
        },
        {
            "from": "chrA:1503-1506:AGTAA",
            "name": "chrA:1503-1506:AGTAA_ref-chrA:1507-1509",
            "sequences": [
                "swap1:1"
            ],
            "to": "ref-chrA:1507-1509"
        },
        {
            "from": "ref-chrA:1503-1506",
            "name": "ref-chrA:1503-1506_ref-chrA:1507-1509",
            "sequences": [
                "REF",
                "swap1:0"
            ],
            "to": "ref-chrA:1507-1509"
        },
        {
            "from": "ref-chrA:1507-1509",
            "name": "ref-chrA:1507-1509_ref-chrA:1510-1659",
            "sequences": [
                "REF",
                "swap1:0",
                "swap1:1"
            ],
            "to": "ref-chrA:1510-1659"
        },
        {
            "from": "ref-chrA:1510-1659",
            "name": "ref-chrA:1510-1659_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from /Users/schen6/Documents/paragraph-tools/share/test-data/genotyping_test_2/chrA.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chrA:1350-1502",
            "reference": "chrA:1350-1502",
            "reference_sequence": "GAGCGTCAAAGGCCCGTCCTATAGACCTGAAGAGTGTTGAGAGTTCTATGGAAAAATTTATAGAGTACTTCCCAGTGTTTTAACTGTAACTGACTTCCATGATCATTTCAGTAATGCAGCCCACATGCATGTTCAAGACTAACACACCGTGCT"
        },
        {
            "name": "chrA:1503-1506:AGTAA",
            "position": "chrA:1503-1506",
            "sequence": "AGTAA"
        },
        {
            "name": "ref-chrA:1503-1506",
            "reference": "chrA:1503-1506",
            "reference_sequence": "GCCC"
        },
        {
            "name": "ref-chrA:1507-1509",
            "reference": "chrA:1507-1509",
            "reference_sequence": "CTT"
        },
        {
            "name": "ref-chrA:1510-1659",
            "reference": "chrA:1510-1659",
            "reference_sequence": "CGTTGACCCTGGTAGAAGTTAGCGGGGCTTGTTTAAGGTCGCGTCGGAATATATGATTTACATAACTGTCACTTTGGGACGCACCCGGCCTTATGGCCATGTGTATTGATAGACTGTCAACCTAACAAGAAAAATTAACGCTTTCCCGAC"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chrA:1350-1502",
                "ref-chrA:1503-1506",
                "ref-chrA:1507-1509",
                "ref-chrA:1510-1659"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "REF",
        "swap1:0",
        "swap1:1"
    ],
    "target_regions": [
        "chrA:1350-1659"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/basic/del-with-nodes-only.json
{
  "model_name": "Sample graph with only nodes specified for a deletion",
  "nodes": [
    {
      "name": "ref-SimpleDeletion:1-40",
      "reference": "SimpleDeletion:1-40",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:41-60",
      "reference": "SimpleDeletion:41-60",
      "sequences": [
        "REF"
      ]
    },
    {
      "name": "ref-SimpleDeletion:61-100",
      "reference": "SimpleDeletion:61-100",
      "sequences": [
        "REF"
      ]
    }
  ],
  "sequencenames": [
    "REF"
  ],
  "target_regions": [
    "SimpleDeletion:1-100"
  ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/insertions/insertion-test-1.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_chr20:149014-149013:CTGAC",
            "to": "chr20:149014-149013:CTGAC"
        },
        {
            "from": "source",
            "name": "source_ref-chr20:149008-149013",
            "to": "ref-chr20:149008-149013"
        },
        {
            "from": "chr20:149014-149013:CTGAC",
            "name": "chr20:149014-149013:CTGAC_ref-chr20:149014-149018",
            "sequences": [
                "HG002_pbsv.INS.49079:1"
            ],
            "to": "ref-chr20:149014-149018"
        },
        {
            "from": "ref-chr20:149008-149013",
            "name": "ref-chr20:149008-149013_chr20:149014-149013:CCATA",
            "sequences": [
                "HG002_pbsv.INS.49079:1"
            ],
            "to": "chr20:149014-149013:CCATA"
        },
        {
            "from": "ref-chr20:149008-149013",
            "name": "ref-chr20:149008-149013_ref-chr20:149014-149018",
            "sequences": [
                "HG002_pbsv.INS.49079:0",
                "REF"
            ],
            "to": "ref-chr20:149014-149018"
        },
        {
            "from": "chr20:149014-149013:CCATA",
            "name": "chr20:149014-149013:CCATA_sink",
            "to": "sink"
        },
        {
            "from": "ref-chr20:149014-149018",
            "name": "ref-chr20:149014-149018_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from ../paragraph-tools/share/test-data/paragraph/insertions/insertion-test-1.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "chr20:149014-149013:CTGAC",
            "position": "chr20:149014-149013",
            "sequence": "CTGAC"
        },
        {
            "name": "ref-chr20:149008-149013",
            "reference": "chr20:149008-149013",
            "reference_sequence": "GAACAA"
        },
        {
            "name": "chr20:149014-149013:CCATA",
            "position": "chr20:149014-149013",
            "sequence": "CCATA"
        },
        {
            "name": "ref-chr20:149014-149018",
            "reference": "chr20:149014-149018",
            "reference_sequence": "CCATA"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr20:149008-149013",
                "ref-chr20:149014-149018"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        },
        {
            "nodes": [
                "ref-chr20:149008-149013",
                "chr20:149014-149013:CCATA"
            ],
            "path_id": "ALT|1",
            "sequence": "ALT"
        },
        {
            "nodes": [
                "chr20:149014-149013:CTGAC",
                "ref-chr20:149014-149018"
            ],
            "path_id": "ALT|2",
            "sequence": "ALT"
        }
    ],
    "sequencenames": [
        "ALT",
        "HG002_pbsv.INS.49079:0",
        "HG002_pbsv.INS.49079:1",
        "REF"
    ],
    "target_regions": [
        "chr20:149008-149018"
    ]
}

=== yangqimeng99/svlearn/bin/paragraph-v2.4a/share/test-data/paragraph/simple/swap-example-2.json
{
    "edges": [
        {
            "from": "source",
            "name": "source_ref-chr5:70243962-70244111",
            "to": "ref-chr5:70243962-70244111"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_ref-chr5:70244112-70244116",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244112-70244116"
        },
        {
            "from": "ref-chr5:70243962-70244111",
            "name": "ref-chr5:70243962-70244111_chr5:70244112-70244116:ATCCG",
            "sequences": [
                "ALT"
            ],
            "to": "chr5:70244112-70244116:ATCCG"
        },
        {
            "from": "ref-chr5:70244112-70244116",
            "name": "ref-chr5:70244112-70244116_ref-chr5:70244117-70244266",
            "sequences": [
                "REF"
            ],
            "to": "ref-chr5:70244117-70244266"
        },
        {
            "from": "chr5:70244112-70244116:ATCCG",
            "name": "chr5:70244112-70244116:ATCCG_ref-chr5:70244117-70244266",
            "sequences": [
                "ALT"
            ],
            "to": "ref-chr5:70244117-70244266"
        },
        {
            "from": "ref-chr5:70244117-70244266",
            "name": "ref-chr5:70244117-70244266_sink",
            "to": "sink"
        }
    ],
    "model_name": "Graph from simple/swap-example-2.vcf",
    "nodes": [
        {
            "name": "source",
            "sequence": "NNNNNNNNNN"
        },
        {
            "name": "ref-chr5:70243962-70244111",
            "reference": "chr5:70243962-70244111"
        },
        {
            "name": "ref-chr5:70244112-70244116",
            "reference": "chr5:70244112-70244116"
        },
        {
            "name": "chr5:70244112-70244116:ATCCG",
            "position": "chr5:70244112-70244116",
            "sequence": "ATCCG"
        },
        {
            "name": "ref-chr5:70244117-70244266",
            "reference": "chr5:70244117-70244266"
        },
        {
            "name": "sink",
            "sequence": "NNNNNNNNNN"
        }
    ],
    "paths": [
        {
            "nodes": [
                "ref-chr5:70243962-70244111",
                "ref-chr5:70244112-70244116",
                "ref-chr5:70244117-70244266"
            ],
            "path_id": "REF|1",
            "sequence": "REF"
        }
    ],
    "sequencenames": [
        "ALT",
        "REF"
    ],
    "target_regions": [
        "chr5:70243962-70244266"
    ]
}
